#ifndef __PANEL_CONF_H
#define __PANEL_CONF_H

#define PANEL_NAME "Synthgirl"

// #define PANEL_COLOR 0x00404840
// #define PANEL_WIDGET_LED_ALPHA 0x60
// #define PANEL_WIDGET_FILL_ALPHA 0x40
// #define PANEL_WIDGET_COLOR_RELEASED 0xFF607260
// #define PANEL_WIDGET_COLOR_POINTED 0xFF809080
// #define PANEL_WIDGET_COLOR_PRESSED 0xFFA08870
// #define PANEL_WIDGET_COLOR_HELPTEXT 0xFF483010

#define DISP_XSIZE 854
#define DISP_YSIZE 480

#define PANEL_SCALE 1
#define PANEL_UNIT_SIZE 46
#define PANEL_UNIT_GAP 4
#define PAN_BORDER 20

#define PAN_BUT_INC ((PANEL_UNIT_SIZE + PANEL_UNIT_GAP) * PANEL_SCALE)

// #define PAN_ELEMENTS_WIDTH ((PANEL_UNIT_SIZE * 4 + PANEL_UNIT_GAP * 3) * PANEL_SCALE)

#define PAN_RBXOFF (PAN_BORDER + PAN_BUT_INC * 3 + (DISP_XSIZE + 2 + PANEL_UNIT_GAP) * PANEL_SCALE)

#define PANEL_SIZE_X (PAN_BORDER * 2 + PAN_BUT_INC * 6 + (DISP_XSIZE + 2 + PANEL_UNIT_GAP) * PANEL_SCALE)
#define PANEL_SIZE_Y (PAN_BORDER * 2 + (DISP_YSIZE + 2) * PANEL_SCALE)

#define FF_VOLUME_ROOT {"../Sd_Card", "./ff_ext"}

#endif // __PANEL_CONF_H